// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdG-daKo45ay7SWQyDN2Pkwttyka_r9S8',
    appId: '1:985420975432:web:62227c656d6cc6abf0f77d',
    messagingSenderId: '985420975432',
    projectId: 'flutterexpenses-devrenatolima',
    authDomain: 'flutterexpenses-devrenatolima.firebaseapp.com',
    databaseURL: 'https://flutterexpenses-devrenatolima-default-rtdb.firebaseio.com',
    storageBucket: 'flutterexpenses-devrenatolima.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdqlkIaTsKGZgBp3nGrWSefmy5YrY3-Xo',
    appId: '1:985420975432:android:2f01d92c247d8f6bf0f77d',
    messagingSenderId: '985420975432',
    projectId: 'flutterexpenses-devrenatolima',
    databaseURL: 'https://flutterexpenses-devrenatolima-default-rtdb.firebaseio.com',
    storageBucket: 'flutterexpenses-devrenatolima.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6fqFy9o1k-LVl9q7ck2LQmMvBNGiy31E',
    appId: '1:985420975432:ios:2cac48356ea1bde4f0f77d',
    messagingSenderId: '985420975432',
    projectId: 'flutterexpenses-devrenatolima',
    databaseURL: 'https://flutterexpenses-devrenatolima-default-rtdb.firebaseio.com',
    storageBucket: 'flutterexpenses-devrenatolima.appspot.com',
    iosClientId: '985420975432-2cu3b42of39hf5nu69e0vt2b8ek36rmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6fqFy9o1k-LVl9q7ck2LQmMvBNGiy31E',
    appId: '1:985420975432:ios:a3f4e4fef82a2b71f0f77d',
    messagingSenderId: '985420975432',
    projectId: 'flutterexpenses-devrenatolima',
    databaseURL: 'https://flutterexpenses-devrenatolima-default-rtdb.firebaseio.com',
    storageBucket: 'flutterexpenses-devrenatolima.appspot.com',
    iosClientId: '985420975432-b3u7t0phrpb5s8hcbon20heci1379j77.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenses.RunnerTests',
  );
}
